### ISSUE TITLE
14A - Layout da tela inicial

### ISSUE THREAD

**Issue by joaoleao87** [marrare/tcoins#10]
**- DESCRIÇÃO**
    
Criar layout para tela inicial

**- PASSO A PASSO**

- [x] estruturar lista de lojas
- [x] organizar layout da tela
- [ ] criar filtros na tela
- [x] pegar dados do endpoint

**- RESULTADO ESPERADO**
 
Ter tela inicial seguindo o layout proposto no airframe

**Comment by marrare** [comment]
Funcionando, porém atraso devido ao componente de busca

**Comment by joaoleao87** [comment]
correções sendo feitas na branch 14-atividade-nilson
