### ISSUE TITLE
16D - Crud de Produtos

### ISSUE THREAD

**Issue by joaoleao87** [marrare/tcoins#19]
**- DESCRIÇÃO**
    
Criar Crud no backend para a classe produtos
fazer ajustes nos métodos existentes

**- PASSO A PASSO**

- [x] Criar service
- [x] criar controller
- [x] produtoController 
- [x] produtoRequestDTO/produtoDTO

**- RESULTADO ESPERADO**
 
Ter endpoints funcionando para produto

**Comment by marrare** [comment]
editar adicionando pontos de dto e users
