### ISSUE TITLE
CRUD de usuarios

### ISSUE THREAD

**Issue by allesson182** [marrare/tcoins#37]
**- DESCRIÇÃO**

Criar Crud no backend para a classe usuarios
fazer ajustes nos métodos existentes

**- PASSO A PASSO**
- [x] Ajustar userController
- [x] criar userRequestDTO
- [x] userDTO
- [x] validar métodos
**- RESULTADO ESPERADO**
 
Ter endpoints funcionando para usuario

**Comment by marrare** [comment]
no userRequestDTO não deve ser enviado codigo_user, token_google ou imagem.

_obs! o codigo_user deve ser gerado no backend, uma identificação simples com 6 caracteres_

**Comment by allesson182** [comment]
feito
