### ISSUE TITLE
2B - Endpoint para listar lojas

### ISSUE THREAD

**Issue by joaoleao87** [marrare/tcoins#9]
**- DESCRIÇÃO**
    
Criar endpoint listar lojas

**- PASSO A PASSO**

- [x] criar endpoint
- [x] testar métodos

**- RESULTADO ESPERADO**
 
Ter endpoint para listagem de lojas

**Comment by marrare** [comment]
Não há consulta considerando filtro como nome da loja e ramo em simultâneo, ou cobrindo todos os cenários. Alterei parte da consulta mas ainda falta.

**Comment by allesson182** [comment]
ajustado para pesquisar separadamente ou simutaneamente
